project:
  type: website
  output-dir: _site

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: documentation.qmd
        text: Docs
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
